
# docker-compose.yml
# This YAML defines three services:
# neo4j: Runs the official neo4j:5 container, exposing ports 7474 (web UI) and 7687 (Bolt).
# ingest: Builds from ./ingest/Dockerfile, mounts ./emails/ for raw data, and loads into Neo4j.
# gui: Builds from ./gui/Dockerfile, runs ai_chat_gui.py in isolation.
# Also defines volumes (neo4j_data, neo4j_logs) to persist DB data.
# This YAML file (YAML format) defines and orchestrates all three services: Neo4j, ingest, and GUI. Save this as docker-compose.yml in your project root.
version: '3.8'
services:
  neo4j:
    image: neo4j:5                        # Official Neo4j Docker image
    container_name: neo4j                 # Container name for easy reference
    environment:
      - NEO4J_AUTH=neo4j/password123      # Username and password for DB
    volumes:
      - neo4j_data:/data                  # Persist database data
      - neo4j_logs:/logs                  # Persist logs
    ports:
      - "7474:7474"                      # HTTP browser UI
      - "7687:7687"                      # Bolt protocol for drivers

  ingest:
    build: ./ingest                        # Build context (ingest/Dockerfile)
    depends_on:
      - neo4j                             # Wait for Neo4j to be ready
    environment:
      - NEO4J_URI=bolt://neo4j:7687       # Bolt URI pointing to Neo4j service
      - NEO4J_USER=neo4j                  # Auth credentials for ingest script
      - NEO4J_PASSWORD=password123
    volumes:
      - ./emails:/app/emails              # Mount local emails folder into container

  gui:
    build: ./gui                           # Build context (gui/Dockerfile)
    depends_on:
      - neo4j                             # Ensure database is up before GUI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass OpenAI key from host
    ports:
      - "5000:5000"                      # (Optional) Expose if web-based

volumes:
  neo4j_data:                             # Named volume for database files
  neo4j_logs:                             # Named volume for logs